apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: php-example
  name: php-example
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: php-example:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/lukeelten/openshift-example-cakephp.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: php:7.1
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ImageChange
  - type: ConfigChange
  - generic:
      secret: b1df06e55fde9753
    type: Generic
  - github:
      secret: bf0d06448df973e9
    type: GitHub
