apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: php-example
  name: php-example
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: docker-registry.default.svc:5000/php-example
