apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    app: nodejs-example
  name: nodejs-example
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: nodejs-example:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/lukeelten/openshift-example-nodejs.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:10
        namespace: openshift
    type: Source
  successfulBuildsHistoryLimit: 5
  triggers:
  - type: ImageChange
  - type: ConfigChange
  - generic:
      secret: 041cd1c8b7f4ac56
    type: Generic
  - github:
      secret: 6ab6b0db9d0c26a9
    type: GitHub
