apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  labels:
    app: nodejs-example
  name: nodejs-example
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: docker-registry.default.svc:5000/nodejs-example
