apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftWebConsole
  creationTimestamp: 2019-05-24T15:31:24Z
  labels:
    app: nodejs-ex
  name: nodejs-ex
  namespace: test
  resourceVersion: "8147"
  selfLink: /apis/build.openshift.io/v1/namespaces/test/buildconfigs/nodejs-ex
  uid: fd290196-7e38-11e9-9a2d-02f10ac2fca6
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: nodejs-ex:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    git:
      ref: master
      uri: https://github.com/openshift/nodejs-ex.git
    type: Git
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:10
        namespace: openshift
    type: Source
  triggers:
  - imageChange:
      lastTriggeredImageID: docker-registry.default.svc:5000/openshift/nodejs@sha256:3cc041334eef8d5853078a0190e46a2998a70ad98320db512968f1de0561705e
    type: ImageChange
  - type: ConfigChange
  - generic:
      secret: 9d29088c65ee86fa
    type: Generic
  - github:
      secret: 751046bc2a9ce275
    type: GitHub
status:
  lastVersion: 1
